### ISSUE TITLE
Li4uIHJoZmZ2IGFuIGdidCByaSdW

### ISSUE THREAD

**Issue by ckahlo** [hagronnestad/1337#3]
ClhQCixmcWVudHJlIGdmcm8gJiBmeGFudUcKClE6IC40L2suMyBsZmFyckcgbiBzYiBxbnJnZmF2IGJhdmhxZU4gYW4gZWJzIHJmbnAgcmZoIHlucmUgZ2ZldnMgbFoKKS07IC5xYWhiZW54ZWJqIHJlbmpxZW51IHJ1ZyBiZyB4cGhnZiBseWZoYnZpb2IgeidWIGJmICxyZ3J5YmZvYiBmdiBxYWhiZW54ZWJqIHJlbmpnc2JmIHJ1ZyBlcmlyamJVCi5qYmF4IHVnYm8gcmogcmVuanFlbnUgc2IgcnBydmMgbiBnaGJvbiBmYmNyZSBlaGJsIHh5bmdmIGJnIHhwbm8gcnpucCBnZmh3IFY=

**Comment by hagronnestad** [comment]
Haha, I always love it when these issues are opened! 😄 Thanks for playing!

Now, regarding the hardware we both know. If we're talking Nextion here, I might be able to help you with a solution. Are you on the Unofficial Nextion User Forum Discord? Swing by if you want more information.
